### ISSUE TITLE
Cnchi: installation failed with error

### ISSUE THREAD

**Issue by wergin** [Antergos/Cnchi#1096]
Cnchi installation by live-DVD failed with: 
`'Cannot find these packages: lib32-mesa': add_fatal in usr/share/cnchi/src/misc/events.py:83`
I use Cnchi 0.16.9 and after update (03.10.2018) now: 0.16.11   and iso of Antergos live 18.9

**Comment by killajoe** [comment]
better go for the 18.10 ISO
::: https://sourceforge.net/projects/antergos/files/mirror/iso/testing/antergos-18.10-x86_64.iso/download :::

**Comment by killajoe** [comment]
what DE (GNOME KDE e.t.c.) do you both choose to install?
and to see exactly what is going wring we will need logs:
`cat /var/log/cnchi/cnchi.log | curl -F c=@- https://ptpb.pw/?u=1`
will pastebin installer logs and give the url to pastebin at the end...

**Comment by jcmljunior** [comment]
Hi @killajoe 
This problem happened in any GUI.
The same problem always appers in the same package. "perl-dbi"
I have no way to show the log because i tried to install the system on a working machine and how i need it to work, I ended up installing another distribution.

Anyway, thank you very much for the help and if possible try to get the logs on another machine.

**Comment by karasu** [comment]
I'm really sorry, but without logs, we cannot pinpoint what's wrong as we cannot reproduce this.
