### ISSUE TITLE
Cnchi 6.28/30/32 freezing while downloading packages.

### ISSUE THREAD

**Issue by Xarin** [Antergos/Cnchi#251]
Trying to get Antergos back on my laptop. Both Cnchi 6.28 and 6.30 are freezing up either the whole machine or sometimes just the installer. It seems to be random freezing up or halting downloading on different packages everytime.

**Comment by karasu** [comment]
[2014-12-30 22:49:42] [pac.py] ERROR: Can't find a package or group called 'mesa-dri'
[2014-12-30 22:49:42] [pac.py] ERROR: Can't find a package or group called 'broadcom-wl'

mesa-dri has been renamed. It's already fixed.
broadcom-wl is in the AUR, that's why Cnchi can't find it. I'll add it to our repo.

Cheers!
