### ISSUE TITLE
Automatically offer keyboard layout matching language

### ISSUE THREAD

**Issue by Mikaela** [Antergos/Cnchi#279]
When I choose to install Antergos, I am asked which language I want and I select Finnish.

Later I am asked which keyboard layout I have and I believe it should suggest Finnish to me, because I selected my language as Finnish. However I am suggested USA.

I think that most of users who select X as language will also want X as keyboard layout instead of Y. 

Possibly related: https://github.com/Antergos/Cnchi/issues/275

**Comment by karasu** [comment]
I'll check this out. Thanks for reporting it!

**Comment by Mikaela** [comment]
Reading the issue tracker more today, it looks like this is possibly duplicate of https://github.com/Antergos/Cnchi/issues/250 ?

**Comment by karasu** [comment]
It looks alike, yes. I thought slovak was the only case!

Thanks again, I'll keep you posted.

**Comment by karasu** [comment]
Fixed in 0.9.x

**Comment by erikdubois** [comment]
During installation I tend to choose for bare installation. Then choose English Uk as language and Belgium as keyboard BUT I end up in QWERTY. 

The whole country works with AZERTY keyboards.

Extra actions for users now:
sudo loadkey be-latin1    in order to have azerty KEYBOARD
We change also the following file to make it permanent
sudo nano /etc/vconsole.conf
We change our keyboard from "be"  to "be-latin1"

Keyboard "be" does not exist!
Could you look into this?

**Comment by Mikaela** [comment]
@erikdubois I think you should open a new issue about this.

**Comment by erikdubois** [comment]
opening a new issue now

**Comment by Mikaela** [comment]
https://github.com/Antergos/Cnchi/issues/331
