### ISSUE TITLE
Email client

### ISSUE THREAD

**Issue by prescott66** [Antergos/Cnchi#293]
In packages.xml is no email client app to install.
Maybe user can select email client in feature tab, or add one for all DE.
i.e. Thunderbird, Evolution, Geary

**Comment by mitchtbaum** [comment]
[Claws](http://claws-mail.org/) has worked well for me for about a year.  I found that it looks great after installing a nicer theme, changing a few settings, and switching to a nicer font.  By default, it looks okay and works very well.

**Comment by axaxs** [comment]
This is a tough one.  At home I use no email client, I imagine the vast majority do not with the prevalence of webmail accounts and interfaces.  At work I used thunderbird, lightning, and the ews calendar provider.  Meaning, I think this could easily become a rathole.  Some want evolution, but do we give them evolution-ews?  If thunderbird, does lightning come with it?  Which language packs?   I'm not opposing, just wondering if this is best left up to the user rather than in the installer.

**Comment by lots0logs** [comment]
I agree @axaxs !

**Comment by Mikaela** [comment]
I never learned to use Evolution, but Thunderbird is nice and I would request Enigmail (GPG-support) to be shipped with it if possible.

**Comment by axaxs** [comment]
Well, I agree that Thunderbird is nicer than Evolution, which is full of bugs and untested.  Seriously, I used 3.16 for a stint and there are no less than 4 bugs that can occur everyday that could make it crash! But enough Evolution bashing - I respect your choice to use Thunderbird with GPG, but don't understand why this should be added to the installer.  I'm still convinced most users don't use a native email client, and the trade-off for someone like yourself is a single pacman command to your choosing upon first boot.  I'm just not seeing the need for the installer to handle the hundreds of email configuration combinations possible.  I'm not saying 'no', not that I have that sole power anyhow, just need convincing as to the real world use case.  As we've seen from this bug already, everyone wants something different...

**Comment by Mikaela** [comment]
> I respect your choice to use Thunderbird with GPG, but don't understand why this should be added to the installer

It's just assumption about Antergos not being so much for normal user and someone using Antergos being subscribed to some mailing lists, maybe Arch Security or something and messages on those being usually signed and even if you didn't use PGP, Enigmail could check the signatures.

**Comment by lots0logs** [comment]
I don't doubt that there are users out there who still use desktop e-mail clients today. However, that does not warrant adding an e-mail client to the default installation nor as a feature that can be enabled/disabled. Our package selection is minimal, by design. It provides only the necessities. We must give careful consideration to all feature requests as we do not want to end up in ***feature creep [1]*** territory. I hope you understand. Thanks for taking the time offer suggestions. Suggestions are always appreciated, even if we don't choose to implement them. 

[1] http://en.wikipedia.org/wiki/Feature_creep

**Comment by karasu** [comment]
@prescott66 and @Mikaela : I'm afraid I'm with the others in this one. Most of current users do not use any desktop mail client, and the ones that use them know very well how to install them.

Oh, and the features screen is already crowded as it is, imho.

Having said that, as @lots0logs said, thanks for your suggestion!
