### ISSUE TITLE
Advanced Mode: Require boot partition for UEFI systems if bootloader installation is enabled

### ISSUE THREAD

**Issue by lots0logs** [Antergos/Cnchi#371]
If the user has chosen to install bootloader on a UEFI system, `/boot/efi` mount point is required. Currently the user is able to continue without specifying the mount point which results in an unbootable system. This was working properly last I checked so it seems to be a regression.

**Comment by karasu** [comment]
Not again! :laughing: 

Just in case you don't remember, code is in method check_mount_points() in advanced.py

**Comment by karasu** [comment]
Oh, as it is now, with grub2 it should enforce it, but with gummiboot doesn't. Do not know why.

**Comment by lots0logs** [comment]
It was a colleague of mine from work that brought this to my attention. He said it happened with Grub2. I will check it out myself ASAP.

**Comment by jscholfield** [comment]
For clarity sake, the mount point determines what partition the kernel will reside on. /boot puts the kernel on the $ESP and /boot/efi puts it on the / partition. This does make a difference depending on the boot loader used. When no boot loader is used, /boot must be the mount point because the UEFI can only directly load kernels from the $ESP. It should also be considered that if multiple distros get installed with /boot as the mount point, there can be issues where multiple kernels are at the root of the $ESP.

The Arch wiki gives this pretty good treatment for reference. It boils down to needing to handle both single OS and dual/multiple boot well, handle no boot loader/manager or boot loaders or boot managers. I'd add that defaults should be determined from what is learned from the user choices during installation and it may be appropriate to ive some users choices, such as users doing their own partitioning for example.

**Comment by jscholfield** [comment]
I recommend these be the boot loader options.
  * For MBR/BIOS- all configs- Grub- common handling if user configs for /boot partition
  * For UEFI/GPT- only linux (1 distro)- EFISTUB w/no boot manager or loader- /boot mount point for ESP
  * For UEFI/GPT- dual boot or multi boot- Grub or systemd-boot (bootctl)- /boot/efi mount point for ESP
Systemd-boot has replaced gummiboot and is included with systemd. Both Grub and Systemd-boot rely on using efibootmgr for writing to the UEFI variables.

**Comment by karasu** [comment]
@lots0logs : Have you got any time to check this out?

**Comment by karasu** [comment]
@lots0logs I can't reproduce it here. There's a bug in the forward button, though.

![antergos uefi](https://cloud.githubusercontent.com/assets/175797/9204989/f2590a1e-405f-11e5-88f7-79cf4caf6964.png)

**Comment by lots0logs** [comment]
@karasu Hmm..his partition layout included two drives (one ssd and one hdd). His existing EFI partition was on the SSD while he was installing Antergos to the HDD. I will try to find some time to look at it soon!

**Comment by karasu** [comment]
@lots0logs : Maybe he forgot to set the mount point? Dunno...

**Comment by lots0logs** [comment]
@karasu I think you might have misunderstood the issue. Cnchi should have shown that the mountpoint was required in the mount checklist but it did not. Furthermore it let him continue without the mount point set which it shouldn't have.

**Comment by karasu** [comment]
>Cnchi should have shown that the mountpoint was required in the mount checklist but it did not.

Oh, then forget my last comment :grin: 

OK. He was using UEFI, I suppose. As you can see in the image, cnchi in fact does ask for /boot/efi if it's run in an UEFI system (not in a BIOS one, of course).

There must be some combination ¿? that makes Cnchi stop asking for a /boot/efi partition.

**Comment by karasu** [comment]
Oh, and I think we can release even if this issue is not yet solved... it's been too long since latest release (again). If you agree I will make 0.9.249 the next 0.10 (and then you can create a new iso with it :grimacing: )

**Comment by lots0logs** [comment]
I'm pretty sure this has been resolved, we can reopen if I am wrong.
