### ISSUE TITLE
cnchi 0.14.104 is on pending

### ISSUE THREAD

**Issue by FilipMB** [Antergos/Cnchi#616]
The latest version of cnchi in stable repo is cnchi-0.14.94-1-any.pkg.tar.xz from 2016-06-05, newer versions of cnchi are only in staging repo.

Also, cinnamon-translations is newer (3.0.2-3) than in arch repo (3.0.2-1).

**Comment by lots0logs** [comment]
>The latest version of cnchi in stable repo is cnchi-0.14.94-1-any.pkg.tar.xz from 2016-06-05, newer versions of cnchi are only in staging repo.

Yes, that's intentional. Packages are only moved into the main repo once we have cleared them.

>Also, cinnamon-translations is newer (3.0.2-3) than in arch repo (3.0.2-1).

This was an oversight. However there's no going backwards now that its done so if you want pacman to stop telling you about it every time you perform a transaction you will have to move the antergos repo so that it appears before the community repo in `/etc/pacman.conf`
