### ISSUE TITLE
Cnchi v0.14.250 stucks at "Checking inter conflicts"

### ISSUE THREAD

**Issue by b1tdust** [Antergos/Cnchi#717]
### Problem:
Can't complete installation because Cnchi stucks at **Checking inter conflicts**

### Log Files
- Link to [/tmp/cnchi-alpm.log](http://paste2.org/ZpGF0eaI)

### Additional Notes: 
Notebook Lenovo Z40-70 with pre-installed Windows 10 on GTP partition system.

**Comment by Yoshi2889** [comment]
nvidia-utils provides nvidia-libgl nowadays because of the libglvnd changes in Arch, but cnchi tries to install nvidia-libgl anyway. Deselecting the NVIDIA proprietary drivers should let it pass.

Removing the references here should fix it:
https://github.com/Antergos/Cnchi/blob/master/cnchi/hardware/nvidia.py#L104

**Comment by karasu** [comment]
@Yoshi2889 you must always check the 0.14.x branch. master is development (and to be honest, not much has been done in this branch).

https://github.com/Antergos/Cnchi/blob/0.14.x/cnchi/hardware/modules/nvidia.py

Thanks anyway!

**Comment by Yoshi2889** [comment]
Oh sorry, thought master would be more up to date than stable. Will keep it
in mind though :)

**Comment by b1tdust** [comment]
@Yoshi2889 thanks. It works by deselecting the nvidia drivers.
Thanks!
