### ISSUE TITLE
Show a personalized error when Internet connection fails

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#80]
Anyway, we could try to detect the problem right? if the connection fails,
we could check if the user has access to the internet and show a
personalized error telling the user that it is something wrong with his
connection.

**Comment by mitchtbaum** [comment]
How about instead of ```is connected to the Internet```, changing to something along the lines of ```can reach network package server```?

A user on IRC reported his installation haled during this check because Cnchi failed to recognize his active connection, seen here: http://i.imgur.com/mFTLQK1.png

I believe this happened because ```has_connection()```'s testing ```url``` machine was/is down, as it is also currently unreachable from my machine (so more people probably have this problem now).

I first thought that a more robust checker might try multiple urls, then I realized, why check any more than the one the user needs.

**Comment by karasu** [comment]
Now, even when Cnchi "thinks" there is no connection, the user will be able to go on.

Cnchi asks Networkmanager if there is a connection, but as sometimes this does not work, like in Virtualbox (don't ask me why), then it also searches for a well known ip.

If these two tests fail, Cnchi shows the "can't connect to the internet" but the user is able to go on.

I'll close this ( @mitchtbaum if you disagree, feel free to comment here again).
