### ISSUE TITLE
Antergos Installation with Cnchi Report Error 136065

### ISSUE THREAD

**Issue by sean-liang** [Antergos/Cnchi#813]
I tried to install Antergos in a VirtualBox vm. The host system is Windows 10 64bit. And the vm use the default NAT network.  The ISO image was downloaded from http://mirrors.antergos.com/iso/release/antergos-17.11-x86_64.iso.torrent.

Then the cnchi reported error 136065 at the last step.

Please check the log for details: [cnchi.log](https://github.com/Antergos/Cnchi/files/1457509/cnchi.log)

**Comment by karasu** [comment]
Hi,

There was some problem with the qt5-styleplugins package that prevented Cnchi to download it.

Have you retried the installation? I can download it here without any problems.

**Comment by HawktheSlayer** [comment]
Hi karasu

I am unable to sign in to the Antergos forum due to a Session Mismatch to report this installation problem, so apologies if this is not the correct route. 

I downloaded Antergos 17.11 and have tried several times to install it.
I keep getting errors about downloading packages and metalinks with various error codes, the last one being 137619.

**Comment by sean-liang** [comment]
Hi Karasu,

Tried the installation again with the same environment and image. It works this time. Sorry for my late response and thank you for your quick reply:)
