### ISSUE TITLE
Put correct distro info in /etc/os-release

### ISSUE THREAD

**Issue by IsaakGroepT** [Antergos/Cnchi#853]
In order for us to programmatically detect which distro we're using, the /etc/os-release file is a great help. However Antergos uses the standard file from Arch and therefore identifies itself as Arch.

There can be some cases where it's interesting to know whether the distro specifically is Antergos, so I suggest modifying the NAME property in the file to Antergos Linux

**Comment by karasu** [comment]
NAME=Antergos
ID=antergos
ID_LIKE=arch
PRETTY_NAME=Antergos
ANSI_COLOR="1;34;40"
HOME_URL="http://www.antergos.com/"
SUPPORT_URL="http://forum.antergos.com/"
BUG_REPORT_URL="http://bugs.antergos.com/"

**Comment by IsaakGroepT** [comment]
That's right :-)

**Comment by lots0logs** [comment]
@karasu We are already doing this. Maybe the file is getting overwritten by a package.

**Comment by killajoe** [comment]
```
oekamprad@empowered64  ~  cat /etc/os-release
NAME="Antergos Linux"
VERSION="18.3-ISO-Rolling"
ID="antergos"
ID_LIKE="arch"
PRETTY_NAME="Antergos Linux"
CPE_NAME="cpe:/o:antergosproject:antergos:18.3"
ANSI_COLOR="1;34;40"
HOME_URL="https://antergos.com/"
SUPPORT_URL="https://forum.antergos.com/"
BUG_REPORT_URL="https://github.com/antergos"
```

**Comment by IsaakGroepT** [comment]
Now that I installed KDE, the file contains the data as submitted by killajoe. In Gnome it was the opposite

**Comment by Omaj7** [comment]
I have Antergos with GNOME as default, I only use GDM instead of LightDM, because of wayland session. This is my output.
```
(Sat Mar-10 13:44:28)-(CPU 4.5%:RAM 39.4%)-(dpomajbik:~)-(216K:39)
> echo $XDG_CURRENT_DESKTOP 
GNOME
(Sat Mar-10 13:44:36)-(CPU 4.8%:RAM 39.4%)-(dpomajbik:~)-(216K:39)
> cat /etc/os-release 
NAME="Antergos Linux"
VERSION="18.2-ISO-Rolling"
ID="antergos"
ID_LIKE="arch"
PRETTY_NAME="Antergos Linux"
CPE_NAME="cpe:/o:antergosproject:antergos:18.2"
ANSI_COLOR="1;34;40"
HOME_URL="https://antergos.com/"
SUPPORT_URL="https://forum.antergos.com/"
BUG_REPORT_URL="https://github.com/antergos"
```

**Comment by IsaakGroepT** [comment]
Verified in my Gnome VM that it contained the correct information. For some reason my real Gnome was different. I guess this issue is solved.

**Comment by eli-schwartz** [comment]
> @karasu We are already doing this. Maybe the file is getting overwritten by a package.

Someone just asked about this on #antergos, and it appears you're being awfully lazy. Instead of providing a custom "filesystem" package you use ours, then the next time we (Arch Linux) push an updated filesystem package it overwrites the modifications made here: https://github.com/Antergos/Cnchi/blob/5427904f414cd1f338434f45adfa0fa2a9ad941c/scripts/postinstall.sh#L369

Please don't do this.

**Comment by karasu** [comment]
I recall that at some point we were packaging filesystem, and then we dropped it, but I don't remember why... @lots0logs ?

**Comment by lots0logs** [comment]
AFAIK, we have never packaged it ourselves. Obviously what we're doing now isn't good but I'd like to avoid repackaging any packages from `core` if we can. One possible solution would be to use alpm hook to update the file when it gets modified by an update to the filesystem package. I'm not sure when I will have time to work on it but I'll do my best to get it done soon.

**Comment by karasu** [comment]
@lots0logs I'm positive we did build it (in the cinnarch times). I'm building it right now just for the fun of doing it... but do not worry, I won't move it from staging.

>One possible solution would be to use alpm hook to update the file when it gets modified by an update to the filesystem package

Yes, I thought of this, too. But this hook should also be in a package of ours?

**Comment by lots0logs** [comment]
Indeed, it would have to be provided by a package. That's not an issue. Its not adding an additional package I am concerned about. I just don't like the idea of us repackaging anything from arch's `core` repo :grimacing:

**Comment by karasu** [comment]
OK, I'll delete it from our repo, then.

**Comment by lots0logs** [comment]
I almost forgot: Thanks for bringing this to our attention @eli-schwartz :smiley:

**Comment by eli-schwartz** [comment]
No problem. :smile: Thanks for looking at this promptly.

A pacman hook looks like a good compromise... :heart: hooks :grin:

**Comment by kq01526** [comment]
@eli-schwartz @lots0logs @karasu 

I realize this is the exact opposite of what is being asked here (kinda), but:

After using the Antergos ISO as an installer (which worked very well, so still grateful for Antergos/Cnchi in general), I have removed the Antergos repo (and all the packages that came pre-installed from it).

Now I would like to make everything say "Arch" instead of "Antergos" like it would on vanilla Arch.

How would I do this?

Regards

**Comment by eli-schwartz** [comment]
Why not just install actual Arch? Vanilla Arch does not support installers like Cnchi, and I don't mean we don't provide it -- I mean we consider the official installation instructions to be an integral part of what it means to install Arch, and what you're doing does not qualify.

This is obviously something I don't wish to condone...

**Comment by kq01526** [comment]
> @eli-schwartz wrote:
> Why not just install actual Arch?

Because, and I am sure you have heard that argument before, using a GUI installer is easier and more convenient. And Antergos seems to be the next best thing of installing vanilla Arch via a GUI installer (could be even better though, see below).

> @eli-schwartz wrote:
> Vanilla Arch does not support installers like Cnchi

Just as I am sure you have heard my previous argument before, I have heard your argument before as well.

But I think you should consider supporting it.

That being said: After having installed Antergos, I really ask myself why Antergos uses it's own repo and packages. As mentioned in the previous post, my reason for removing the Antergos repo and removing all the packages that came pre-installed from it was because of https://github.com/Antergos/antergos-packages/issues/300 which made me realize there does not really seem to be a reason to use the Antergos repo (other than maybe for installing the OS) when there is everything in the Arch repos and AUR anyway and packages in the Arch repos/AUR have less bugs and often are more up-to-date.

> @eli-schwartz wrote:
> This is obviously something I don't wish to condone...

Although it's obvious for me that you would reply something like that, the reason is not immediately obvious to me. Just wondering: What if the Antergos developers would decide to ditch their own Antergos repo and would only use the Arch repos and AUR from the get-go? Would you then support it?

And, yeah, I know you do not support the AUR either (which I also do not really understand, since it's practically kinda integral to Arch. I know you will reply that it's not, but that would only apply to the theory, not to the actual practice.).

**Comment by eli-schwartz** [comment]
> using a GUI installer is easier and more convenient

One of the core Arch philosophies is that this is only superficially true.

> Just as I am sure you have heard my previous argument before, I have heard your argument before as well.
> But I think you should consider supporting it.

This is not the right place for discussing whether the Arch philosophy is deeply flawed because of exclusivity. 

Thank you for acknowledging that we've heard your argument before...

> As mentioned in the previous post

Seemingly edited in after I commented.

> Although it's obvious for me that you would reply something like that, the reason is not immediately obvious to me. Just wondering: What if the Antergos developers would decide to ditch their own Antergos repo and would only use the Arch repos and AUR from the get-go? Would you then support it?

If they did not provide their own repo, and they used the official installation guide then yes we would support it because it would no longer be Antergos. OTOH it would no longer be Antergos so I'm not sure where you're going with this...

Note that we do not support systems installed with our own installation media and using only official repos, if they were installed via e.g. youtube tutorials instead of the installation guide. I'm fairly positive this is not news to anyone who has even obliquely heard of Arch.

> I realize this is the exact opposite of what is being asked here (kinda), but:

So, uh, ask elsewhere?

**Comment by kq01526** [comment]
> @eli-schwartz wrote:
> Seemingly edited in after I commented.

Wrong. Edited in **_while_** you where commenting.

**Comment by lots0logs** [comment]
@kq01526 What you want to do is essentially reap all the benefits of our hard work and tell the world you did it yourself. I don't mean that in a literal sense but I think you'll get my point. We do not condone nor do we encourage users to do what you are trying to do. The fact that you have to ask how to do it is, in fact, the reason why you shouldn't do it.

Anyway, this thread has gone way off-topic. The original issue reported here has been fixed so I am closing this.

**Comment by searedvandal** [comment]
We just talked about this on IRC. My Antergos install from last Friday says it's Arch again, not Antergos. The way to fix it would either to package the filesystem package for Antergos, or add a pacman hook after filesystem gets updated to get it back to Antergos.

**Comment by eli-schwartz** [comment]
> Anyway, this thread has gone way off-topic. The original issue reported here has been fixed so I am closing this.

Well, apparently it is not. Did you ever actually package this hook? Because I keep recently hearing about this not actually being fixed, due to peoples' systems still claiming to be Arch.
