### ISSUE TITLE
Enable i3 installation

### ISSUE THREAD

**Issue by karasu** [Antergos/Cnchi#902]
Check that i3 is working as it is and enable it.

**Comment by searedvandal** [comment]
Do I need to grab the testing iso in order to test the i3 install?

**Comment by searedvandal** [comment]
Alright, I'll give it a go and see how it fares.

**Comment by searedvandal** [comment]
Launched cnchi with the -z parameter. Chose i3, left everything else as Cnchi is set by default. Got as far as integrity check, where 2 packages failed the integrity checks due to invalid checksum or corrupted packages. I've linked the logs below.

cnchi-alpm.log - https://ptpb.pw/hykg
cnchi.log - https://ptpb.pw/xgFu
pacman-boot.log - https://ptpb.pw/IT1J

**Comment by searedvandal** [comment]
Ok. I have no dealt with the first headache. Issues with the mouse in i3. I'm testing in a VirtualBox VM.
When I start and lightdm shows up, mouse works just fine. I log in, and if I don't click anywhere until kalu news shows up, I can click OK on kalu and the mouse click is registered. If I for example click on the network notification first, and then try to close the kalu news window, mouse click doesn't register.

I fired up the terminal and started troubleshooting a bit. Never encountered this issue before. First I noticed that libinput list-devices returned a segmentation fault. Checked the arch forums and yeah, the latest update apparently gives some this error. I grabbed the version from before the latest update from the arch archives, installed it, set it to ignore in pacman and rebooted. Same issues with mouse. Mouse clicks register fine in lightdm and if I don't click on anything until kalu shows up I can close that window. But as soon as I click anywhere else on screen, mouse clicks stop registering.

Installed xf86-input-synaptics (noticed that there is this 50-synaptics.conf in the /etc/X11/xorg.conf.d/ directory so thought I would give it a shot) and rebooted. Now mouse clicks seems to register in i3 as well. I open firefox and sure enough, I can open new tabs and all the normal stuff with the mouse buttons. Shut down the VM, take a snapshot and figure I solved it.

Starts the VM up again to play around in i3, after I type password, I click on the network notification window. Now I'm back at mouse clicks not registering anywhere in i3 again. Checked running processes, it all looked pretty normal. Decided to restart dbus.service. Logged back in, and now mouse clicks are registering again. This is where I'm at now. I have not rebooted again.

To me it seems like the mouse troubles are somehow connected to the notifications? Since when I click on the notification clicks stops registering. Moving the cursor around the screen have worked fine all the time, it's mouse clicks and the scroll wheel that's not registering.

**Comment by karasu** [comment]
@searedvandal many thanks for your testing. I'm really busy right now with other issues. I'll have a look at this asap. Thanks again!

**Comment by killajoe** [comment]
fail to install:
cnchi-alpm.log https://pastelink.net/ewvn
cnchi.log https://pastelink.net/ewvr

**Comment by karasu** [comment]
i3 configuration needs a bit of love, but it's working now. Closing.
